config/routes.rb
Feathers::Application.routes.draw do
  # session control
  devise_for :users

  # allow easy sign in
  devise_scope :user do
    get "login", to: "devise/sessions#new"
  end

  # base resource routes
  resources :addresses, :jobs, :job_categories, :packages, :pictures, :posts, :projects, :project_categories, :resume_categories, :resume_entries

  # posts jobs and projects have pictures
  resources :posts, :jobs, :projects do
    resources :pictures
  end

  # projects and jobs have packages
  resources :projects, :jobs do
    resources :packages
  end

  # job categories have jobs
  resources :job_categories do
    resources :jobs
  end

  # project categories have projects
  resources :project_categories do
    resources :projects
  end

  # resume categories have resume entries
  resources :resume_categories do
    resources :resume_entries
  end

  # map resume to placeholder resumes controller index
  match 'resume', to: 'resumes#index'

  # map contact to resume index
  match 'contact', to: 'contact#index'

  # map submit to contact submit
  match 'submit', to: 'contact#submit'

  # we want posts#index to be our landing page
  root to: 'posts#index'
end

app/models/job_category.rb
# Seperates out Different types of work
class JobCategory < ActiveRecord::Base
  # default order by rank to prioritize
  default_scope order 'rank asc'
  # allow getters and setters for these attributes
  attr_accessible :name, :rank

  # has many Job
  has_many :jobs, dependent: :destroy
end

app/controllers/job_categories_controller.rb
# Deals with JobCategory related restfull routes
class JobCategoriesController < ApplicationController
  # load initial controller variables if authorized by Ability
  load_and_authorize_resource
  # serve up html routes
  respond_to :html

  # simple create method on true sends a good notice
  def create
    flash[:notice] = 'Job Category Created' if @job_category.save
    respond_with @job_category
  end

  # simple update method on success sends a good method
  def update
    flash[:notice] = 'Job Category Updated' if @job_category.update_attributes! params[:job_category]
    respond_with @job_category
  end

  # almost default destroy, on success sends a good message
  def destroy
    flash[:notice] = 'Job Category Deleted' if @job_category.destroy
    respond_with @job_category
  end
end

app/views/job_categories/_form.html.haml
= form_for job_category, html: { class: 'text-center' } do |f|
  = render partial: 'shared/form_error', collection: job_category.errors.full_messages
  %p= f.text_field :name, placeholder: 'name'
  %p= f.text_field :rank, placeholder: 'rank'
  %p.clearfix= f.submit class: 'btn btn-primary pull-right'

app/views/job_categories/edit.html.haml
- content_for :title do
  Editing Job Category
= render 'form', job_category: @job_category

app/views/job_categories/index.html.haml
- content_for :title do
  Job Categories
%table.table.table-striped
  %thead
    %tr
      %th name
      %th rank
  %tbody
    - @job_categories.each do |job_category|
      %tr
        %td= link_to job_category.name, job_category
        %td= job_category.rank
.btn-group.pull-left.clearfix
  = link_to 'create job category', new_job_category_path, class: 'btn btn-primary'
  = link_to 'back', jobs_path, class: 'btn'

app/views/job_categories/new.html.haml
- content_for :title do
  Creating Job Category
= render 'form', job_category: @job_category

app/views/job_categories/show.html.haml
- content_for :title do
  = @job_category.name
%table.table.table-striped
  %thead
    %tr
      %th name
      %th rank
  %tbody
    - @job_category.jobs.each do |job|
      %tr
        %td= link_to job.name, [@job_category, job]
        %td= job.rank
%p.clearfix
  .btn-group.pull-left
    = link_to 'back', job_categories_path, class: 'btn'
    = link_to 'create job', new_job_category_job_path(@job_category), class: 'btn btn-primary'
    = link_to 'edit', edit_job_category_path(@job_category), class: 'btn btn-primary'
  = button_to 'destroy', @job_category, method: :delete, class: 'btn btn-danger pull-right'