config/routes.rb
Feathers::Application.routes.draw do
  # session control
  devise_for :users

  # allow easy sign in
  devise_scope :user do
    get "login", to: "devise/sessions#new"
  end

  # base resource routes
  resources :addresses, :jobs, :job_categories, :packages, :pictures, :posts, :projects, :project_categories, :resume_categories, :resume_entries

  # posts jobs and projects have pictures
  resources :posts, :jobs, :projects do
    resources :pictures
  end

  # projects and jobs have packages
  resources :projects, :jobs do
    resources :packages
  end

  # job categories have jobs
  resources :job_categories do
    resources :jobs
  end

  # project categories have projects
  resources :project_categories do
    resources :projects
  end

  # resume categories have resume entries
  resources :resume_categories do
    resources :resume_entries
  end

  # map resume to placeholder resumes controller index
  match 'resume', to: 'resumes#index'

  # map contact to resume index
  match 'contact', to: 'contact#index'

  # map submit to contact submit
  match 'submit', to: 'contact#submit'

  # we want posts#index to be our landing page
  root to: 'posts#index'
end

app/models/job.rb
# Module represents past jobs I've been employed to do
# this module could use a date attribute
class Job < ActiveRecord::Base
  # default order by rank
  default_scope order 'rank asc'
  # Allow getters and estters for these values
  attr_accessible :blurb, :detail, :employer, :name, :rank

  # it has one JobCategory
  belongs_to :job_category
  # it has many JobsPicture, essentially a join table
  has_many :jobs_pictures, dependent: :destroy
  has_many :jobs_packages, dependent: :destroy

  # a through relations ship to Picture
  has_many :packages, through: :jobs_packages, dependent: :destroy
  has_many :pictures, through: :jobs_pictures, dependent: :destroy
end

app/controllers/jobs_controller.rb
# Deal with restfull routes for Job
class JobsController < ApplicationController
  # ensure the User is allowed by Ability
  load_and_authorize_resource
  # serve up html
  respond_to :html
  # load the parent category on routes that need it for forms
  before_filter :load_category, only: [:new, :create, :edit]

  # override index to load categories
  def index
    @job_categories = JobCategory.page params[:page]
  end

  # simple create method on true sends a good notice
  def create
    flash[:notice] = 'Job Created' if @job_category.jobs.create params[:job]
    respond_with @job.job_category, @job
  end

  # simple update method on success sends a good method
  def update
    flash[:notice] = 'Job Updated' if @job.update_attributes! params[:job]
    respond_with @job.job_category, @job
  end

  # almost default destroy, on success sends a good message
  def destroy
    flash[:notice] = 'Job Deleted' if @job.destroy
    respond_with @job.job_category
  end

  private
    # load the supplied catgory for appropriate routes
    def load_category
      @job_category = JobCategory.find params[:job_category_id]
    end
end

app/views/jobs/_form.html.haml
= form_for [job_category, job], html: { class: 'text-center' } do |f|
  = render partial: 'shared/form_error', collection: job.errors.full_messages
  %p= f.text_field :name, placeholder: 'name'
  %p= f.text_field :rank, placeholder: 'rank'
  %p= f.text_field :employer, placeholder: 'empoyer'
  %p= f.text_area :blurb, placeholder: 'blurb', class: 'input-xxlarge'
  %p= f.text_area :detail, placeholder: 'detail', class: 'input-xxlarge'
  %p.clearfix= f.submit class: 'btn btn-primary pull-right'

app/views/jobs/edit.html.haml
- content_for :title do
  Editing Job
= render 'form', job: @job, job_category: @job_category
= render 'shared/author_helper', owner: @job

app/views/jobs/index.html.haml
- content_for :browser do
  \/dev/boone/clients
- content_for :title do
  Clients
.main-banner= image_tag 'davis_death_star.jpg'
- if current_user.try :admin?
  %p.clearfix= link_to 'manage jobs', job_categories_path, class: 'btn pull-right'
= render partial: 'shared/category', collection: @job_categories
.text-center= paginate @job_categories, theme: 'twitter-bootstrap'

app/views/jobs/new.html.haml
- content_for :title do
  Creating Job
= render 'form', job: @job, job_category: @job_category
= render 'shared/author_helper', owner: @job

app/views/jobs/show.html.haml
- content_for :browser do
  \/dev/boone/clients/#{@job.name}
- content_for :title do
  = @job.name
- if current_user.try :admin?
  %p.clearfix
    .btn-group.pull-right
      = link_to 'back', job_category_path(@job.job_category), class: 'btn'
      = link_to 'edit job', edit_job_category_job_path(@job.job_category, @job), class: 'btn btn-primary'
      = link_to 'manage packages', job_packages_path(@job), class: 'btn btn-warning'
      = link_to 'manage pictures', job_pictures_path(@job), class: 'btn btn-warning'
    = button_to 'destroy job', [@job.job_category, @job], method: :delete, class: 'btn btn-danger'
= render partial: 'shared/category_item_display', locals: { item: @job }