config/routes.rb
Feathers::Application.routes.draw do
  # session control
  devise_for :users

  # allow easy sign in
  devise_scope :user do
    get "login", to: "devise/sessions#new"
  end

  # base resource routes
  resources :addresses, :jobs, :job_categories, :packages, :pictures, :posts, :projects, :project_categories, :resume_categories, :resume_entries

  # posts jobs and projects have pictures
  resources :posts, :jobs, :projects do
    resources :pictures
  end

  # projects and jobs have packages
  resources :projects, :jobs do
    resources :packages
  end

  # job categories have jobs
  resources :job_categories do
    resources :jobs
  end

  # project categories have projects
  resources :project_categories do
    resources :projects
  end

  # resume categories have resume entries
  resources :resume_categories do
    resources :resume_entries
  end

  # map resume to placeholder resumes controller index
  match 'resume', to: 'resumes#index'

  # map contact to resume index
  match 'contact', to: 'contact#index'

  # map submit to contact submit
  match 'submit', to: 'contact#submit'

  # we want posts#index to be our landing page
  root to: 'posts#index'
end

app/models/resume_category.rb
# Classify resume into types of skillsets
# see ResumeEntry
class ResumeCategory < ActiveRecord::Base
  # default order by rank for display
  default_scope order 'rank asc'
  attr_accessible :name, :rank

  has_many :resume_entries, dependent: :destroy
end

app/controllers/resume_categories_controller.rb
# Deals with ResumeCategory related routes
class ResumeCategoriesController < ApplicationController
  # ensure that User is alowed by Ability and load up the resource
  load_and_authorize_resource
  # serve up html
  respond_to :html

  # simple create method on true sends a good notice
  def create
    flash[:notice] = 'Resume Category Created' if @resume_category.save
    respond_with @resume_category
  end

  # simple update method on success sends a good method
  def update
    flash[:notice] = 'Resume Category Updated' if @resume_category.update_attributes! params[:resume_category]
    respond_with @resume_category
  end

  # almost default destroy, on success sends a good message
  def destroy
    flash[:notice] = 'Resume Category Deleted' if @resume_category.destroy
    respond_with @resume_category
  end
end

app/views/resume_categories/_form.html.haml
= form_for resume_category, html: { class: 'text-center' } do |f|
  = render partial: 'shared/form_error', collection: resume_category.errors.full_messages
  %p= f.text_field :name, placeholder: 'name'
  %p= f.text_field :rank, placeholder: 'rank'
  %p.clearfix= f.submit class: 'btn btn-primary pull-right'

app/views/resume_categories/_resume_category.html.haml
%p.resume-category #{resume_category.name}
%ul.unstyled
  = render resume_category.resume_entries

app/views/resume_categories/edit.html.haml
- content_for :title do
  Editing Resume Category
= render 'form', resume_category: @resume_category

app/views/resume_categories/index.html.haml
- content_for :title do
  Resume Categories
%table.table.table-striped
  %thead
    %tr
      %th name
      %th rank
  %tbody
    - @resume_categories.each do |resume_category|
      %tr
        %td= link_to resume_category.name, resume_category
        %td= resume_category.rank
.btn-group.pull-left.clearfix
  = link_to 'create resume category', new_resume_category_path, class: 'btn btn-primary'
  = link_to 'back', resume_path, class: 'btn'

app/views/resume_categories/new.html.haml
- content_for :title do
  Creating Resume Category
= render 'form', resume_category: @resume_category

app/views/resume_categories/show.html.haml
- content_for :title do
  = @resume_category.name
%table.table.table-striped
  %thead
    %tr
      %th name
      %th rank
  %tbody
    - @resume_category.resume_entries.each do |resume_entry|
      %tr
        %td= link_to resume_entry.name, [@resume_category, resume_entry]
        %td= resume_entry.rank
%p.clearfix
  .btn-group.pull-left
    = link_to 'create resume entry', new_resume_category_resume_entry_path(@resume_category), class: 'btn btn-primary'
    = link_to 'back', resume_categories_path, class: 'btn'
    = link_to 'edit', edit_resume_category_path(@resume_category), class: 'btn btn-primary'
  = button_to 'destroy', @resume_category, method: :delete, class: 'btn btn-danger pull-right clearfix'