config/routes.rb
Feathers::Application.routes.draw do
  # session control
  devise_for :users

  # allow easy sign in
  devise_scope :user do
    get "login", to: "devise/sessions#new"
  end

  # base resource routes
  resources :addresses, :jobs, :job_categories, :packages, :pictures, :posts, :projects, :project_categories, :resume_categories, :resume_entries

  # posts jobs and projects have pictures
  resources :posts, :jobs, :projects do
    resources :pictures
  end

  # projects and jobs have packages
  resources :projects, :jobs do
    resources :packages
  end

  # job categories have jobs
  resources :job_categories do
    resources :jobs
  end

  # project categories have projects
  resources :project_categories do
    resources :projects
  end

  # resume categories have resume entries
  resources :resume_categories do
    resources :resume_entries
  end

  # map resume to placeholder resumes controller index
  match 'resume', to: 'resumes#index'

  # map contact to resume index
  match 'contact', to: 'contact#index'

  # map submit to contact submit
  match 'submit', to: 'contact#submit'

  # we want posts#index to be our landing page
  root to: 'posts#index'
end

app/models/project.rb
# holds personal projects has many Picture and Package
# belongs to a Category
class Project < ActiveRecord::Base
  # default order by rank
  default_scope order 'rank asc'
  belongs_to :project_category
  attr_accessible :blurb, :detail, :name, :rank, :team

  belongs_to :project_category

  has_many :packages_projects, dependent: :destroy
  has_many :pictures_projects, dependent: :destroy

  has_many :packages, through: :packages_projects, dependent: :destroy
  has_many :pictures, through: :pictures_projects, dependent: :destroy
end

app/controllers/projects_controller.rb
# Deals with Project related routes
class ProjectsController < ApplicationController
  # ensure that User is allowed by Ability
  load_and_authorize_resource
  # serve up html
  respond_to :html
  # load the parent reouts project
  before_filter :load_category, only: [:new, :create, :edit]

  # paginate our categories
  def index
    @project_categories = ProjectCategory.page params[:page]
  end

  # simple create method on true sends a good notice
  def create
    flash[:notice] = 'Project Created' if @project_category.projects.create params[:project]
    respond_with @project.project_category, @project
  end

  # simple update method on success sends a good method
  def update
    flash[:notice] = 'Project Updated' if @project.update_attributes! params[:project]
    respond_with @project.project_category, @project
  end

  # almost default destroy, on success sends a good message
  def destroy
    flash[:notice] = 'Project Deleted' if @project.destroy
    respond_with @project.project_category
  end

  private
    # helper to load parent routes category for nested projects
    def load_category
      @project_category = ProjectCategory.find params[:project_category_id]
    end
end

app/views/projects/_form.html.haml
= form_for [project_category, project], html: { class: 'text-center' } do |f|
  = render partial: 'shared/form_error', collection: project.errors.full_messages
  %p= f.text_field :name, placeholder: 'name'
  %p= f.text_field :rank, placeholder: 'rank'
  %p= f.text_field :team, placeholder: 'team'
  %p= f.text_area :blurb, placeholder: 'blurb', class: 'input-xxlarge'
  %p= f.text_area :detail, placeholder: 'detail', class: 'input-xxlarge'
  %p.clearfix= f.submit class: 'btn btn-primary pull-right'

app/views/projects/edit.html.haml
- content_for :title do
  Editing Project
= render 'form', project: @project, project_category: @project_category
= render 'shared/author_helper', owner: @project

app/views/projects/index.html.haml
- content_for :browser do
  \/dev/boone/projects
- content_for :title do
  Projects
.main-banner= image_tag 'davis_death_star.jpg'
- if current_user.try :admin?
  %p.clearfix= link_to 'manage projects', project_categories_path, class: 'btn pull-right'
= render partial: 'shared/category', collection: @project_categories
.text-center= paginate @project_categories, theme: 'twitter-bootstrap'

app/views/projects/new.html.haml
- content_for :title do
  Creating Project
= render 'form', project: @project, project_category: @project_category
= render 'shared/author_helper', owner: @project

app/views/projects/show.html.haml
- content_for :browser do
  \/dev/boone/projects/#{@project.name}
- content_for :title do
  = @project.name
- if current_user.try :admin?
  %p.clearfix
    .btn-group.pull-right
      = link_to 'back', project_category_path(@project.project_category), class: 'btn'
      = link_to 'edit project', edit_project_category_project_path(@project.project_category, @project), class: 'btn btn-primary'
      = link_to 'manage packages', project_packages_path(@project), class: 'btn btn-warning'
      = link_to 'manage pictures', project_pictures_path(@project), class: 'btn btn-warning'
    = button_to 'destroy project', [@project.project_category, @project], method: :delete, class: 'btn btn-danger clearfix'
= render partial: 'shared/category_item_display', locals: { item: @project }